#!/bin/sh

msg=temporal.server.api.schedule.v1.StartScheduleArgs
fileorstdin=()

for arg; do
  case "$arg" in
    temporal.*.*) msg=$arg ;;
    *) fileorstdin=($arg) ;;
  esac
done

base64 -d "${fileorstdin[@]}" | ( cd ~/t/temporal ; protoc -I=proto/internal -I=proto/dependencies -I=proto/api --decode=$msg $(find proto/internal/ -name \*.proto) )
